# Generated by Django 2.0.2 on 2018-03-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('slug', models.SlugField(max_length=256, unique=True)),
                ('event_place', models.CharField(max_length=256)),
                ('event_start', models.DateTimeField()),
                ('event_end', models.DateTimeField()),
                ('event_key', models.CharField(max_length=8)),
                ('event_parent', models.CharField(max_length=256)),
                ('event_fullname', models.CharField(max_length=256)),
                ('event_age_from', models.PositiveIntegerField()),
                ('event_age_to', models.PositiveIntegerField()),
                ('event_organizer', models.CharField(max_length=256)),
                ('event_judge', models.CharField(max_length=256)),
                ('event_sec', models.CharField(max_length=256)),
                ('event_logo', models.CharField(max_length=256)),
                ('event_logo_print', models.CharField(max_length=256)),
                ('event_logo_dim', models.PositiveIntegerField()),
                ('event_team_type', models.PositiveIntegerField()),
                ('event_team_n', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
